# Generated by Django 6.0.3 on 2026-03-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Remarques optionnelles sur la vente.', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='vente',
            name='reference',
            field=models.CharField(default='', editable=False, help_text='Code unique auto-généré (ex: VNT-2026-0001)', max_length=20, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total TTC'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='completee', max_length=20, verbose_name='Statut'),
        ),
    ]
