# Generated by Django 6.0.3 on 2026-03-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_populate_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='reference',
            field=models.CharField(editable=False, help_text='Code unique auto-généré (ex: VNT-2026-0001)', max_length=20, unique=True, verbose_name='Référence'),
        ),
    ]
