# Generated by Django 6.0.3 on 2026-03-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('dci', models.CharField(blank=True, default='', max_length=200, verbose_name='Dénomination Commune Internationale')),
                ('forme', models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('suppositoire', 'Suppositoire'), ('gouttes', 'Gouttes'), ('autre', 'Autre')], default='comprime', max_length=20, verbose_name='Forme galénique')),
                ('dosage', models.CharField(blank=True, default='', max_length=50, verbose_name='Dosage')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.PositiveIntegerField(default=10, verbose_name="Stock minimum (seuil d'alerte)")),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('ordonnance_requise', models.BooleanField(default=False, verbose_name='Ordonnance requise')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('est_actif', models.BooleanField(default=True, help_text='False = supprimé (soft delete)', verbose_name='Actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
    ]
